use super::*;

// ── Error Display ───────────────────────────────────────────────

/// `Sha1Mismatch` display must include the path, expected, and actual hashes.
///
/// Users diagnose source-detection failures from error messages, so all
/// three fields must appear in the formatted output.
#[test]
fn verify_error_display_sha1_mismatch() {
    let err = VerifyError::Sha1Mismatch {
        path: "test.mix".into(),
        expected: "aaa".into(),
        actual: "bbb".into(),
    };
    let msg = err.to_string();
    assert!(msg.contains("test.mix"), "missing path in: {msg}");
    assert!(msg.contains("aaa"), "missing expected hash in: {msg}");
    assert!(msg.contains("bbb"), "missing actual hash in: {msg}");
}

/// `FileNotFound` display must include the missing file name.
///
/// The path is the only diagnostic information the user has to locate
/// the problem, so it must appear verbatim in the error message.
#[test]
fn verify_error_display_file_not_found() {
    let err = VerifyError::FileNotFound {
        path: "gone.mix".into(),
    };
    let msg = err.to_string();
    assert!(msg.contains("gone.mix"), "missing path in: {msg}");
}

// ── Manifest serialization ──────────────────────────────────────

/// An `InstalledContentManifest` must survive a TOML round-trip unchanged.
///
/// The manifest is persisted to disk as TOML; any field that silently
/// drops during serialization or deserialization would cause false
/// verification failures on next launch.
#[test]
fn manifest_serialization_roundtrip() {
    let mut files = BTreeMap::new();
    files.insert(
        "allies.mix".to_string(),
        FileDigest {
            blake3: "aa".repeat(32),
            size: 1024,
        },
    );
    files.insert(
        "soviet.mix".to_string(),
        FileDigest {
            blake3: "bb".repeat(32),
            size: 2048,
        },
    );

    let original = InstalledContentManifest {
        version: CONTENT_MANIFEST_VERSION,
        game: "ra".to_string(),
        content_version: "v1".to_string(),
        files,
    };

    let toml_str = toml::to_string(&original).unwrap();
    let restored: InstalledContentManifest = toml::from_str(&toml_str).unwrap();

    assert_eq!(original.version, restored.version);
    assert_eq!(original.game, restored.game);
    assert_eq!(original.content_version, restored.content_version);
    assert_eq!(original.files.len(), restored.files.len());
    for (path, digest) in &original.files {
        let rd = restored.files.get(path).expect("missing file entry");
        assert_eq!(digest.blake3, rd.blake3);
        assert_eq!(digest.size, rd.size);
    }
}

// ── Blake3Scratch ───────────────────────────────────────────────

/// `Blake3Scratch::hash_file` must produce the same digest as `blake3_file`.
///
/// The scratch variant is a performance optimization; it must be functionally
/// identical to the one-shot `blake3_file` function or manifests generated by
/// one path would not verify correctly against manifests generated by the other.
#[test]
fn scratch_hash_matches_blake3_file() {
    let tmp = std::env::temp_dir().join("cnc-verify-scratch");
    let _ = fs::remove_dir_all(&tmp);
    fs::create_dir_all(&tmp).unwrap();

    let path = tmp.join("data.bin");
    fs::write(&path, b"scratch buffer test data").unwrap();

    let direct = blake3_file(&path).unwrap();
    let mut scratch = Blake3Scratch::new();
    let scratched = scratch.hash_file(&path).unwrap();
    assert_eq!(direct, scratched);

    let _ = fs::remove_dir_all(&tmp);
}

/// Reusing a `Blake3Scratch` across multiple files must yield independent, correct hashes.
///
/// The scratch pattern resets the hasher between files.
/// If the reset were missing, earlier file bytes would leak into later digests,
/// causing false corruption reports for every file after the first.
#[test]
fn scratch_reuse_produces_correct_hashes() {
    let tmp = std::env::temp_dir().join("cnc-verify-scratch-reuse");
    let _ = fs::remove_dir_all(&tmp);
    fs::create_dir_all(&tmp).unwrap();

    let path_a = tmp.join("a.bin");
    let path_b = tmp.join("b.bin");
    fs::write(&path_a, b"file A content").unwrap();
    fs::write(&path_b, b"file B different content").unwrap();

    let mut scratch = Blake3Scratch::new();
    let hash_a = scratch.hash_file(&path_a).unwrap();
    let hash_b = scratch.hash_file(&path_b).unwrap();

    // Hashes must differ (different content).
    assert_ne!(hash_a, hash_b);

    // Rehashing must produce the same result (hasher properly reset).
    let hash_a2 = scratch.hash_file(&path_a).unwrap();
    assert_eq!(hash_a, hash_a2);

    let _ = fs::remove_dir_all(&tmp);
}
