// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2025–present Iron Curtain contributors

//! HTTP/torrent download definitions for all supported games.
//!
//! Download metadata is maintained in `data/downloads.toml` — a plain-text
//! TOML file embedded at compile time via `include_str!`. This design serves
//! two purposes:
//!
//! 1. **Easy maintenance** — info hashes, mirror URLs, web seeds, and SHA-1
//!    values change over time (new mirrors, torrent creation, hash updates).
//!    Editing a TOML file is simpler than modifying Rust struct literals.
//!
//! 2. **Closed content set** — the P2P engine is hardcoded to distribute
//!    *only* the packages listed in this file. It cannot be repurposed as a
//!    general-purpose BitTorrent client. Only EA-declared freeware (Red Alert
//!    since 2008, Tiberian Dawn since 2007, Tiberian Sun since 2010) has
//!    download entries.
//!
//! ## Legal basis
//!
//! - **Red Alert**: EA-declared freeware (2008-08-31)
//! - **Tiberian Dawn**: EA-declared freeware (2007-08-31), GPL-3.0 source (2025-02)
//! - **Tiberian Sun**: EA-declared freeware (2010), includes Firestorm expansion
//! - **No other games** have download packages — Dune 2, Dune 2000, RA2,
//!   and Generals are local-source-only.

use std::sync::LazyLock;

use serde::Deserialize;

use crate::{DownloadId, DownloadPackage};

// ── Embedded download manifest ────────────────────────────────────────

/// Raw TOML content from `data/downloads.toml`, embedded at compile time.
/// This is the single source of truth for all downloadable content.
const DOWNLOADS_TOML: &str = include_str!("../data/downloads.toml");

/// Wrapper struct for TOML deserialization of the `[[download]]` array.
#[derive(Deserialize)]
struct DownloadManifest {
    download: Vec<DownloadPackage>,
}

/// Parsed download packages from `data/downloads.toml`.
///
/// Parsed once on first access. The TOML is embedded at compile time so
/// any syntax error is caught on the first test run, not at deployment.
static DOWNLOADS_PARSED: LazyLock<Vec<DownloadPackage>> = LazyLock::new(|| {
    // The TOML is compile-time embedded data — a parse failure here means
    // the data file has a syntax or schema error that must be fixed before
    // shipping. Panicking is correct: this is a build-time data integrity
    // check, not a runtime error path.
    let manifest: DownloadManifest = toml::from_str(DOWNLOADS_TOML)
        .expect("data/downloads.toml is embedded at compile time and must be valid TOML");
    manifest.download
});

/// Returns all HTTP/torrent download packages across all games.
///
/// The returned slice lives for `'static` because it is backed by a
/// `LazyLock` in a `static` variable.
pub fn all_downloads() -> &'static [DownloadPackage] {
    &DOWNLOADS_PARSED
}

// ── Embedded .torrent files ───────────────────────────────────────────
//
// Each `.torrent` file is generated by `cnc-content torrent-create` and
// embedded at compile time via `include_bytes!`. They contain:
//
// - Full torrent metadata (piece hashes, file size, name)
// - BEP 19 `url-list` web seed URLs pointing to HTTP mirrors
// - Tracker announce URLs from `data/trackers.txt`
//
// With these embedded, the downloader can write a `.torrent` file to disk
// and hand it to any BT client — downloads start immediately from HTTP
// mirrors (web seeds) with zero BitTorrent peers required. As users share
// the torrent, pieces flow via P2P too, reducing mirror load.
//
// To regenerate after changing mirrors or adding packages:
//   cnc-content torrent-create --output data/torrents
//   cp data/torrents/*.torrent docs/torrents/  # for GitHub Pages

// ── Compiled mirror cache ──────────────────────────────────────────
//
// Mirror URLs are stored directly in `data/downloads.toml` in the
// `mirrors` array of each `[[download]]` entry. A GitHub Action
// (`update-mirrors.yml`) periodically fetches every non-empty
// `mirror_list_url` and updates the `mirrors` array in-place.
// IoC validation runs against ALL project domains before any PR is
// created.
//
// These provide a compile-time baseline of known-good mirrors that
// works even if the runtime mirror list fetch fails or is blocked.
// The runtime fetch supplements these with any mirrors added between
// releases.

/// Returns the compile-time cached mirror list for a download package.
///
/// Returns `None` if no mirrors are cached (e.g. IC-hosted packages
/// whose infrastructure is not yet live, or packages that use
/// `direct_urls` only).
///
/// Mirror URLs live in the `mirrors` array of each `[[download]]`
/// entry in `data/downloads.toml` — the single source of truth.
pub fn compiled_mirrors(id: DownloadId) -> Option<&'static [String]> {
    let dl = all_downloads().iter().find(|d| d.id == id)?;
    if dl.mirrors.is_empty() {
        None
    } else {
        Some(&dl.mirrors)
    }
}

/// Returns the embedded `.torrent` file bytes for a download package, or
/// `None` if no `.torrent` has been generated yet (e.g. IC-hosted packages
/// whose mirror infrastructure is not yet live).
///
/// The returned `.torrent` file contains BEP 19 web seed URLs, so
/// downloads work with zero BitTorrent peers — the BT client fetches
/// pieces directly from the HTTP mirrors via Range requests.
pub fn embedded_torrent(id: DownloadId) -> Option<&'static [u8]> {
    match id {
        // ── Red Alert (OpenRA mirrors) ────────────────────────────────
        DownloadId::RaQuickInstall => {
            Some(include_bytes!("../data/torrents/raquickinstall.torrent"))
        }
        DownloadId::RaBaseFiles => Some(include_bytes!("../data/torrents/rabasefiles.torrent")),
        DownloadId::RaAftermath => Some(include_bytes!("../data/torrents/raaftermath.torrent")),
        DownloadId::RaCncDesert => Some(include_bytes!("../data/torrents/racncdesert.torrent")),

        // ── Tiberian Dawn ─────────────────────────────────────────────
        DownloadId::TdBaseFiles => Some(include_bytes!("../data/torrents/tdbasefiles.torrent")),
        DownloadId::TdCovertOps => Some(include_bytes!("../data/torrents/tdcovertops.torrent")),
        DownloadId::TdGdiIso => Some(include_bytes!("../data/torrents/tdgdiiso.torrent")),
        DownloadId::TdNodIso => Some(include_bytes!("../data/torrents/tdnodiso.torrent")),

        // ── Archive.org full disc sets ────────────────────────────────
        // RaFullDiscs and RaFullSet use Archive.org's own multi-file
        // torrents, which are actively seeded by Archive.org infra.
        // We don't embed those — users get them from archive.org/download.
        DownloadId::RaFullDiscs | DownloadId::RaFullSet => None,

        // ── IC-hosted packages (not yet seeded) ──────────────────────
        // These DownloadIds exist as enum variants for future packages.
        // No .torrent until content ZIPs are built and mirrors go live.
        DownloadId::RaMusic
        | DownloadId::RaMoviesAllied
        | DownloadId::RaMoviesSoviet
        | DownloadId::RaMusicCounterstrike
        | DownloadId::RaMusicAftermath
        | DownloadId::TdMusic
        | DownloadId::TdMoviesGdi
        | DownloadId::TdMoviesNod
        | DownloadId::TsMusic
        | DownloadId::TsMovies => None,

        // ── TS OpenRA mirror packages ────────────────────────────────
        // No .torrent yet — SHA-1 not confirmed for these packages.
        DownloadId::TsBaseFiles | DownloadId::TsQuickInstall | DownloadId::TsExpand => None,

        // ── TS disc ISOs (cnc-comm.com) ──────────────────────────────
        // No .torrent yet — will be generated after downloading and
        // hashing the ZIPs via `cnc-content torrent-create`.
        DownloadId::TsGdiIso | DownloadId::TsNodIso | DownloadId::TsFirestormIso => None,
    }
}
