// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2025–present Iron Curtain contributors

//! RA1 content package definitions — what the game needs to run.
//!
//! Each entry mirrors an OpenRA `ContentPackage` from `mods/ra-content/mod.yaml`
//! but expressed as Rust const data for compile-time validation.
//! File lists and source mappings match OpenRA exactly.

use crate::{ContentPackage, DownloadId, PackageId, SourceId};

/// All RA1 content packages.
///
/// The first three (`Base`, `AftermathBase`, `CncDesert`) are required for
/// the game to launch. The rest are optional enhancements (music, movies).
pub static ALL_PACKAGES: &[ContentPackage] = &[
    // ── Required packages ──────────────────────────────────────────────
    ContentPackage {
        id: PackageId::Base,
        title: "Base Game Content",
        required: true,
        test_files: &[
            "allies.mix",
            "conquer.mix",
            "interior.mix",
            "hires.mix",
            "lores.mix",
            "local.mix",
            "speech.mix",
            "russian.mix",
            "snow.mix",
            "sounds.mix",
            "temperat.mix",
        ],
        sources: &[
            SourceId::AlliedDisc,
            SourceId::SovietDisc,
            SourceId::TheFirstDecade,
            SourceId::SteamTuc,
            SourceId::OriginTuc,
            SourceId::SteamRemastered,
            SourceId::OriginRemastered,
        ],
        download: Some(DownloadId::BaseFiles),
    },
    ContentPackage {
        id: PackageId::AftermathBase,
        title: "Aftermath Expansion",
        required: true,
        test_files: &[
            "expand/expand2.mix",
            "expand/hires1.mix",
            "expand/lores1.mix",
            // Loose Aftermath AUD files — exact names from OpenRA's mod.yaml.
            "expand/chrotnk1.aud",
            "expand/fixit1.aud",
            "expand/jburn1.aud",
            "expand/jchrge1.aud",
            "expand/jcrisp1.aud",
            "expand/jdance1.aud",
            "expand/jjuice1.aud",
            "expand/jjump1.aud",
            "expand/jlight1.aud",
            "expand/jpower1.aud",
            "expand/jshock1.aud",
            "expand/jyes1.aud",
            "expand/madchrg2.aud",
            "expand/madexplo.aud",
            "expand/mboss1.aud",
            "expand/mhear1.aud",
            "expand/mhotdig1.aud",
            "expand/mhowdy1.aud",
            "expand/mhuh1.aud",
            "expand/mlaff1.aud",
            "expand/mrise1.aud",
            "expand/mwrench1.aud",
            "expand/myeehaw1.aud",
            "expand/myes1.aud",
        ],
        sources: &[
            SourceId::AftermathDisc,
            SourceId::TheFirstDecade,
            SourceId::SteamTuc,
            SourceId::OriginTuc,
            SourceId::SteamRemastered,
            SourceId::OriginRemastered,
        ],
        download: Some(DownloadId::Aftermath),
    },
    ContentPackage {
        id: PackageId::CncDesert,
        title: "C&C Desert Tileset",
        required: true,
        test_files: &["cnc/desert.mix"],
        sources: &[
            SourceId::TheFirstDecade,
            SourceId::Cnc95,
            SourceId::SteamCnc,
            SourceId::OriginCnc,
            SourceId::SteamRemastered,
            SourceId::OriginRemastered,
        ],
        download: Some(DownloadId::CncDesert),
    },
    // ── Optional packages ──────────────────────────────────────────────
    ContentPackage {
        id: PackageId::Music,
        title: "Red Alert Music",
        required: false,
        test_files: &["scores.mix"],
        sources: &[
            SourceId::AlliedDisc,
            SourceId::SovietDisc,
            SourceId::TheFirstDecade,
            SourceId::SteamTuc,
            SourceId::OriginTuc,
            SourceId::SteamRemastered,
            SourceId::OriginRemastered,
        ],
        download: None,
    },
    ContentPackage {
        id: PackageId::MoviesAllied,
        title: "Allied Campaign Movies",
        required: false,
        test_files: &[
            "movies/aagun.vqa",
            "movies/aftrmath.vqa",
            "movies/ally1.vqa",
            "movies/ally10.vqa",
            "movies/ally10b.vqa",
            "movies/ally11.vqa",
            "movies/ally12.vqa",
            "movies/ally14.vqa",
            "movies/ally2.vqa",
            "movies/ally4.vqa",
            "movies/ally5.vqa",
            "movies/ally6.vqa",
            "movies/ally8.vqa",
            "movies/ally9.vqa",
            "movies/allyend.vqa",
            "movies/allymorf.vqa",
            "movies/apcescpe.vqa",
            "movies/assess.vqa",
            "movies/battle.vqa",
            "movies/binoc.vqa",
            "movies/bmap.vqa",
            "movies/brdgtilt.vqa",
            "movies/crontest.vqa",
            "movies/cronfail.vqa",
            "movies/destroyr.vqa",
            "movies/dud.vqa",
            "movies/elevator.vqa",
            "movies/flare.vqa",
            "movies/frozen.vqa",
            "movies/grvestne.vqa",
            "movies/landing.vqa",
            "movies/masasslt.vqa",
            "movies/mcv.vqa",
            "movies/mcv_land.vqa",
            "movies/montpass.vqa",
            "movies/oildrum.vqa",
            "movies/overrun.vqa",
            "movies/prolog.vqa",
            "movies/redintro.vqa",
            "movies/shipsink.vqa",
            "movies/shorbom1.vqa",
            "movies/shorbom2.vqa",
            "movies/shorbomb.vqa",
            "movies/snowbomb.vqa",
            "movies/soviet1.vqa",
            "movies/sovtstar.vqa",
            "movies/spy.vqa",
            "movies/tanya1.vqa",
            "movies/tanya2.vqa",
            "movies/toofar.vqa",
            "movies/trinity.vqa",
        ],
        sources: &[
            SourceId::AlliedDisc,
            SourceId::TheFirstDecade,
            SourceId::SteamTuc,
            SourceId::OriginTuc,
            SourceId::SteamRemastered,
            SourceId::OriginRemastered,
        ],
        download: None,
    },
    ContentPackage {
        id: PackageId::MoviesSoviet,
        title: "Soviet Campaign Movies",
        required: false,
        test_files: &[
            "movies/aagun.vqa",
            "movies/airfield.vqa",
            "movies/ally1.vqa",
            "movies/allymorf.vqa",
            "movies/averted.vqa",
            "movies/beachead.vqa",
            "movies/bmap.vqa",
            "movies/bombrun.vqa",
            "movies/countdwn.vqa",
            "movies/cronfail.vqa",
            "movies/double.vqa",
            "movies/dpthchrg.vqa",
            "movies/execute.vqa",
            "movies/flare.vqa",
            "movies/landing.vqa",
            "movies/mcvbrdge.vqa",
            "movies/mig.vqa",
            "movies/movingin.vqa",
            "movies/mtnkfact.vqa",
            "movies/nukestok.vqa",
            "movies/onthprwl.vqa",
            "movies/periscop.vqa",
            "movies/prolog.vqa",
            "movies/radrraid.vqa",
            "movies/redintro.vqa",
            "movies/search.vqa",
            "movies/sfrozen.vqa",
            "movies/sitduck.vqa",
            "movies/slntsrvc.vqa",
            "movies/snowbomb.vqa",
            "movies/snstrafe.vqa",
            "movies/sovbatl.vqa",
            "movies/sovcemet.vqa",
            "movies/sovfinal.vqa",
            "movies/soviet1.vqa",
            "movies/soviet2.vqa",
            "movies/soviet3.vqa",
            "movies/soviet4.vqa",
            "movies/soviet5.vqa",
            "movies/soviet6.vqa",
            "movies/soviet7.vqa",
            "movies/soviet8.vqa",
            "movies/soviet9.vqa",
            "movies/soviet10.vqa",
            "movies/soviet11.vqa",
            "movies/soviet12.vqa",
            "movies/soviet13.vqa",
            "movies/soviet14.vqa",
            "movies/sovmcv.vqa",
            "movies/sovtstar.vqa",
            "movies/spotter.vqa",
            "movies/strafe.vqa",
            "movies/take_off.vqa",
            "movies/tesla.vqa",
            "movies/v2rocket.vqa",
        ],
        sources: &[
            SourceId::SovietDisc,
            SourceId::TheFirstDecade,
            SourceId::SteamTuc,
            SourceId::OriginTuc,
        ],
        download: None,
    },
    ContentPackage {
        id: PackageId::MusicCounterstrike,
        title: "Counterstrike Music",
        required: false,
        test_files: &[
            "expand/2nd_hand.aud",
            "expand/araziod.aud",
            "expand/backstab.aud",
            "expand/chaos2.aud",
            "expand/shut_it.aud",
            "expand/twinmix1.aud",
            "expand/under3.aud",
            "expand/vr2.aud",
        ],
        sources: &[
            SourceId::CounterstrikeDisc,
            SourceId::SteamTuc,
            SourceId::OriginTuc,
            SourceId::SteamRemastered,
            SourceId::OriginRemastered,
        ],
        download: None,
    },
    ContentPackage {
        id: PackageId::MusicAftermath,
        title: "Aftermath Music",
        required: false,
        test_files: &[
            "expand/await.aud",
            "expand/bog.aud",
            "expand/float_v2.aud",
            "expand/gloom.aud",
            "expand/grndwire.aud",
            "expand/rpt.aud",
            "expand/search.aud",
            "expand/traction.aud",
            "expand/wastelnd.aud",
        ],
        sources: &[
            SourceId::AftermathDisc,
            SourceId::SteamTuc,
            SourceId::OriginTuc,
            SourceId::SteamRemastered,
            SourceId::OriginRemastered,
        ],
        download: None,
    },
];
